apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-anyuid
  namespace: basic-nginx
subjects:
  - kind: ServiceAccount
    name: default
    namespace: basic-nginx
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
